# Generated by Django 5.2.1 on 2025-05-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='その他', max_length=100),
            preserve_default=False,
        ),
    ]
