# Generated by Django 5.2.1 on 2025-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='days_before',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
