# Generated by Django 5.2.1 on 2025-06-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
