# Generated by Django 5.2.1 on 2025-06-30 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_category_is_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True)), fields=('title', 'is_template', 'user'), name='unique_template_title_per_user'),
        ),
    ]
