# Generated by Django 5.2.1 on 2025-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='original_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
