# Generated by Django 5.2.1 on 2025-06-20 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_is_public_task_original_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='original_title',
        ),
        migrations.AddField(
            model_name='task',
            name='original_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='todo.task'),
        ),
    ]
