# Generated by Django 5.2.1 on 2025-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='days_before',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
