# Generated by Django 5.2.1 on 2025-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_category_days_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
