# Generated by Django 5.2.1 on 2025-06-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_original_title_task_original_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='original_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
