# Generated by Django 5.2.1 on 2025-06-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_category_days_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='days_before',
            field=models.IntegerField(default=0),
        ),
    ]
