# Generated by Django 5.2.1 on 2025-06-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
