# Generated by Django 5.1.7 on 2025-06-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='display_name',
            field=models.CharField(choices=[('nickname', 'ニックネームで表示'), ('anonymous', '非公開で表示')], default='nickname', max_length=10),
        ),
    ]
