# Generated by Django 5.2.1 on 2025-06-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='created',
            new_name='created_at',
        ),
    ]
