# Generated by Django 5.2.1 on 2025-06-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailchangetoken',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.AddField(
            model_name='emailchangetoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
